### PR TITLE
list db pagination fix

### PR DESCRIPTION
**Pull request by rmaleh**
Please see https://github.com/kovihq/sqltools-athena-driver/issues/29 for the full context. The TLDR is that only up to 100 databases in a single Athena catalog were being returned. The root cause of this is that the AWS Athena API uses pagination to return results, and use the 'NextToken' response field, if it exists, to make subsequent calls to retrieve the next set of 100 databases.

I tested this locally on both an Athena datasource with fewer than 100 databases and an Athena datasource with more than 100 database. In both cases, the complete list of databases was correctly returned.

### CODE REVIEW

**Comment by rmaleh** [comment]
Can somebody please review this?

**Review by JohniMichels — APPROVED** [review]
LGTM

**Comment by rmaleh** [comment]
@brunoventura, can you please review/sign-off?

**Review by brunoventura — APPROVED** [review]
LGTM

**Pull request merged**
